### ISSUE TITLE
Implement a "not found" route

### ISSUE THREAD

**Issue by andres-condezo** [hendridg/metrics-webapp#6]
https://github.com/hendridg/metrics-webapp/blob/36ef084202ceb5f93ccc69cd7a4262b63665688c/src/App.js#L10-L13

Hi @hendridg :wave: 

You did a great job as always, but I think you could add a "not found" route by adding the following line of code:
`<Route path="*" element={<NotFoundPage />} />`

You can find more information at the following link:
https://www.kindacode.com/article/react-router-dom-implement-a-not-found-404-route/

**Comment by hendridg** [comment]
Hi @andres-condezo :hand: 

Thank you, I forgat that, I will

<img src="https://media2.giphy.com/media/Ra7qHOOr080dY5xpW3/giphy.gif"/>
